systemd --user start catdownload
systemd --user start catfetch
systemd --user start catgrid
systemd --user start catpersistence
systemd --user start catreport
systemd --user start catstat
systemd --user start cattag
systemd --user start catwebapi
systemd --user start catwebui
systemd --user start resistanceapi
