systemctl --user start catdownload
systemctl --user start catfetch
systemctl --user start catgrid
systemctl --user start catreport
systemctl --user start catstat
systemctl --user start cattag
systemctl --user start catwebapi
systemctl --user start catwebui
systemctl --user start resistanceapi
