#!/usr/bin/env python3

import json
import time

import requests
import tabulate

r = requests.get('http://localhost:6000/status').json()

nodes = r['nodes']
running = [x['jobs'] for x in nodes.values()]
queue = r['queue']

tbl = list()
for node_name, node in nodes.items():
    tbl.append([node_name, str(len(node['jobs']))])

print(tabulate.tabulate(tbl, headers=['Name', 'Jobs'], tablefmt='psql'))
